### ISSUE TITLE
[Question] Desktop File Indexing

### ISSUE THREAD

**Issue by abose** [fergiemcdowall/search-index#118]
Hi,
   [Brackets](https://github.com/adobe/brackets) is an open source editor and we are looking at improving the Find in Files search capabilities in brackets. I stumbled upon this repository which seems to be very good for our use case. The main purpose is to index all the files in a project and allow for more advanced search queries. I have the following queries about the functionality provided by this library- sorry if these questions seem introductory.

1. We have a list of open projects, can we switch the search index on the fly as projects are changed.
2. Does the search engine watch the filesystem for changes and automatically update the index (or is the index based out of abstract documents).
3. Does it have support for regex search?
4. I see that there have been no releases since 2013, is it safe to run master branch? Can you give an info on the release cycles?
5. Do you recommend this search library for desktop file indexing?

Thanks and regards,
Arun.
Brackets.io

**Comment by mewwts** [comment]
1. I suggest having all files in one index, adding a field `project` on the document so that you can filter on and retrieve only relevant docs. It should also be possible to maintain separate indices. 
2. search-index operates on JSON documents, as such, it would be your job to watch the filesystem and represent the files as documents in the index. 
3. I don't think it supports regex as of now. Have we looked at this @fergiemcdowall?
4. It's merely a result of a bit sloppy github-ness. We will work on getting this a bit more streamlined. With that said the project is semi-regularly released on npm. 
5. I think search-index would do fantastic for this problem and please do not hesitate asking for help or contribute back with PRs or issues.

**Comment by fergiemcdowall** [comment]
Hi Arun

Regarding

>  I see that there have been no releases since 2013

`search-index` is under fairly constant development, and we dont really use the github release functionality. https://www.npmjs.com/package/search-index always has the latest stable version

**Comment by fergiemcdowall** [comment]
We are looking to get more actively involved in dropping `search-index` into other projects, so please let us know if there is anything that we can do :)

**Comment by abose** [comment]
Thanks @fergiemcdowall 
It would be helpful if you could answer the following questions too.
When we delete documents from the index, does the change reflect instantaneously?  
How much memory does the indexer consume in ram, say for an index of  20k files?
Also is it possible to use regex queries with some workarounds?

The usual project size for brackets is around a couple of thousand text files. We were just evaluating/ experimenting on what advanced search features we could bundle with brackets at this stage. One being fuzzy search instead of the current `full string` or `regex` queries that we are currently limited with.

**Comment by fergiemcdowall** [comment]
Yes, deletions change the index instantaneously

Memory usage is generally quite low, since the system is based on levelDB.

It sounds like your typical project size of 2-20k files really hits the sweet spot for ´search-index´.

We are available for hire, and we help a lot of big organisations with this stuff- just sayin ;)

**Comment by abose** [comment]
Thanks @fergiemcdowall  for answering all the queries .
Have added this to our boards at https://trello.com/c/xR7EFyvT/1423-indexing-and-fuzzy-search-support . We[As well as community contributors] usually prioritize stories to be taken from the trello boards based on feature requests. 
Thanks again for the help :)
Closing as answered.
