### ISSUE TITLE
running 2 node services on for search and one for index

### ISSUE THREAD

**Issue by leerlemoniii** [fergiemcdowall/search-index#163]
I am trying to create a couchdb change feed search config.... Have the index working great, and the search running great, but can not run both at the same time because of leveldb database locks staying open.  

Is there a way to close those locks when the service is sitting in wait mode? or ???

**Comment by mewwts** [comment]
Hi @leerlemoniii, thanks for getting in touch! :+1: 

This is an issue with leveldb, see https://github.com/google/leveldb#limitations. The only thing I can suggest from the top of my head is running the two services in the same process.

Although... Since one of your usecases is read only (search), a potential fix could be to do an actual filesystem copy of the index, and run the search using that leveldb index. There are of course some challenges here; i.e. when do you copy the index, shutting down the read-only process etc. 

But the short answer is no, you can't run two processes on the same search-index (leveldb instance).

**Comment by fergiemcdowall** [comment]
A levelDB (and therefore a `search-index`) can only be run by one process at a time.

You can close a `search-index` by using the [`close method`](https://cdn.rawgit.com/fergiemcdowall/search-index/better_docs/doc/api/module-search-index.html#~close) (see the tests for examples of how to use it). Opening and closing indexes is really fast, and is often a practical way to "share" a `search-index` between processes

You could also consider [Norch](https://github.com/fergiemcdowall/norch). Norch is basically a `search-index` that is available on http, so you can have as many programs connecting to it as you want.

**Comment by leerlemoniii** [comment]
so norch is a frontend for search-index (it looks lika anyways), so can I use my already existing index (and search-index code) with norch running the search part of the process?

**Comment by fergiemcdowall** [comment]
Yes, prooooobably

The idea would be to run Norch as a stand alone server, and then communicate with it by using HTTP requests

**Comment by leerlemoniii** [comment]
ok thanks for the help

**Comment by leerlemoniii** [comment]
actually ended up rewriting to make this work all in one process... and seems to be working fine.  Will be running this against 3-5 million fairly large records eventually so need to test speed in those conditions next... will keep you informed.
