### ISSUE TITLE
Use with MongoDB?

### ISSUE THREAD

**Issue by danielflippance** [fergiemcdowall/search-index#246]
Loving your Node.js native search index. It looks like the index is always stored on the filesystem. Do you have any sample code that integrates search-index with MongoDB and stores the index there? Or a recommended fork/repo which does that?

**Comment by fergiemcdowall** [comment]
You initialize a `levelup` instance with `mongodown`, and then you pass it to `search-index` as the `indexes` property

So something like this should work (off the top of my head):

```javascript
const levelup = require('levelup')
const mongodown = require('mongodown')
const searchindex = require('search-index')

levelup('localhost/my-database', {
  db: require('mongodown')
}, function (err, levelUpDb) {
  searchindex({
    indexes: levelUpDb
  }, function(err, si)) {
    
    //if all went to plan "si" is now your seach engine with a mongo backend

  }
})
```

I see now from looking at that code that it would be great to make it cleaner. Users need to understand the whole levelUp/levelDown world in order to get this to work and that is probably unnecessary. On the other hand, this way the initiated user has very fine grained control over the nature of the backend.
