### ISSUE TITLE
"deletable" means deletable entries / documents in the index?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#268]
Just reading a little, and got unsure, so thought it could be good to make the documentation a little better.

[deletable](https://github.com/fergiemcdowall/search-index/blob/master/doc/create.md#deletable) means deletable entries in the index?

**Comment by fergiemcdowall** [comment]
When the index is deletable, it stores the values of all the keys in the index that are associated with every document so that when the document is deleted, all the index entries are also tidied up.

Storing delete keys takes up a fair bit of space, so if you just have an index that is **only** being read from, and index size is an issue, then you might want to set `deletable: false`. This might be the case when replicating the index into the browser- you don't want it to be altered, and you want it to be as small as possible.

When an index has `deletable: false` you can add documents with an ID that **isn't** already in use, but you cannot add documents with an ID that **is** in use (since the old doc would be deleted, before the new is added).

That said, I wonder if changing the name of this parameter to `readonly` would make it more intuitive

**Comment by eklem** [comment]
Yes, `readonly` won't interfere with the notion of deleting the whole index, which is still possible.

**Comment by ConnorKrammer** [comment]
@fergiemcdowall Just chiming in on the semantics: readonly is good, but perhaps carries an unintended implication that the index can’t be updated at all after creation (when in fact it can).

**Comment by fergiemcdowall** [comment]
@ConnorKrammer yes, my feelings as well...

**Comment by fergiemcdowall** [comment]
@eklem indeed

**Comment by eklem** [comment]
Ok, this is the general config setup, and no wonder both `deletable` and `readonly` rings a little wrong, since there is nothing about documents/items.

How about `deletableItems`, `itemsDeletable` or `itemsReadonly`?

**Comment by ConnorKrammer** [comment]
I don’t like the first one much, but either of the latter two work for me. If I had to pick, I’d probably go for `itemsReadonly`.

**Comment by eklem** [comment]
`itemsReadonly` is my favorite too. In any way, `items` should come first. @fergiemcdowall ?

**Comment by fergiemcdowall** [comment]
I prefer anything "deletable" because thats more meaningful that anything "readonly". So `itemsDeletable`, `deletableItems`, `canDeleteItems` or similar

**Comment by ConnorKrammer** [comment]
I prefer “readonly” better because of its more precise semantic fit—you can’t delete items, and you can’t modify them. That seems to fit the definition of readonly well. 

 

“deletable”, on the other hand, leaves an ambiguity where changes to the items are concerned.

**Comment by fergiemcdowall** [comment]
Yes, we need something that means "only add-able"

**Comment by eklem** [comment]
`itemsAddonly` ?

**Comment by ConnorKrammer** [comment]
The issue with the semantics here is that there are three basic operations:

1.      Add item

2.      Modify item

3.      Delete item

 

We want to indicate that the last two are illegal, while allowing the first. Syntax like “can’t delete” isn’t great because it only explicitly disallows a single operation. Syntax like “only add” is better, but requires the user to consciously consider that modifying an item is one of the three operations. Add and delete are polar opposites and therefore fairly obvious, but modifying items may not be on the user’s mind while in the process of adding items to the index—perhaps they think that modification is a separate type of operation (i.e. they think the list of operations above only consists of add and delete, which would mean that “only add” doesn’t affect modification).

 

Readonly, however, is a well-established concept in the programming world—it indicates non-deletion and non-modification, but does not disallow creation in the first place. In my opinion, it’s the most semantically accurate.

**Comment by fergiemcdowall** [comment]
Oooh- I like addOnly

**Comment by fergiemcdowall** [comment]
addReadOnly

**Comment by fergiemcdowall** [comment]
I just noticed that `deletable` is not working as expected. Fixing it and making some tests now

**Comment by fergiemcdowall** [comment]
The concept of "deletability" is removed in the latest version. All docs are always deletable.
