### ISSUE TITLE
teaser highlights partial matches

### ISSUE THREAD

**Issue by nbonamy** [fergiemcdowall/search-index#272]
I think that even if I perform a full word search via .search, the teaser highlights partial matches if a partial matches comes before the full-word match. Anyone has seen the same behavior?

Thanks

**Comment by fergiemcdowall** [comment]
Could you give an example? :)

**Comment by nbonamy** [comment]
Ok found an "easy" one. I took the simple-node-js-example and changed the search terms to "export" only then changed line 17 to display teaser instead of body.

In that case, the second result (BAHIA COCOA REVIEW) hightlights a partial match first:
middlemen, <span class="sc-em">export</span>ers and processors.

Hope you will be able to reproduce!
Nicolas

**Comment by fergiemcdowall** [comment]
Hmmm- teaser is basically a wrapper around https://www.npmjs.com/package/search-context. Any improvements to this functionality have to be done there. If you can condense the problem down to a `search-context` bug, it might be possible to fix.

**Comment by fergiemcdowall** [comment]
I've been looking into teaser functionality today.

The way it works now is a bit of a trade-off, since it is quite fast, and does pure pattern matching- so for short single-word queries, the behaviour can be a bit funky. On the plus side, you get "free" basic [lemmatisation](http://nlp.stanford.edu/IR-book/html/htmledition/stemming-and-lemmatization-1.html), and punctuation is preserved.

Matching and grouping whole words is fairly trivial (at least for european languages), but then you lose punctuation and lemmatisation.

Teaser generation is a pretty big field with a lot of competing requirements, so I'm a bit wary of enshrining any one approach in `search-index`, other than a really basic, out of the box, works-sort-of-ok-for-most-users approach.

It should be fairly easy to make a "query pipeline" to get the functionality you require, and that seems to be the way forward in this case.
