### ISSUE TITLE
Math has no method log10 on node.js v0.10.42

### ISSUE THREAD

**Issue by jcortega** [fergiemcdowall/search-index#291]
The Math object does not seem to have log10 method in node.js v0.10.42. 
`
Sun Jun 05 2016 16:40:08 GMT+0000 (UTC) TypeError: Object #<Object> has no method 'log10'
    at /root/Zenoss/api/node_modules/search-index/node_modules/search-index-searcher/searcher.js:461:34
    at /root/Zenoss/api/node_modules/search-index/node_modules/search-index-searcher/node_modules/lodash.foreach/node_modules/lodash._baseeach/index.js:182:11
    at baseForOwn (/root/Zenoss/api/node_modules/search-index/node_modules/search-index-searcher/node_modules/lodash.foreach/node_modules/lodash._baseeach/index.js:93:20)
    at /root/Zenoss/api/node_modules/search-index/node_modules/search-index-searcher/node_modules/lodash.foreach/node_modules/lodash._baseeach/index.js:151:14
    at forEach (/root/Zenoss/api/node_modules/search-index/node_modules/search-index-searcher/node_modules/lodash.foreach/index.js:65:10)
    at /root/Zenoss/api/node_modules/search-index/node_modules/search-index-searcher/searcher.js:460:7
    at /root/Zenoss/api/node_modules/search-index/node_modules/levelup/lib/levelup.js:230:7
`

**Comment by fergiemcdowall** [comment]
Hmmm- we don't test `search-index` against 0.10.x anymore in order to make use of the newer JS features, so there is some stuff (like this) that doesnt work. Swapping out the `log` method with `log10` would probably still calculate adequate relevance, so if you fancy going into the code of `node_modules/search-index-searcher` you could fix that one line, however, there would be a lot of stuff that wouldn't work unless you have `--harmony` available

I'm sort of leaning towards not fixing any `0.10.x` issues because it is so easy to upgrade to more recent nodes.

**Comment by fergiemcdowall** [comment]
Are you totally bound to node 0.10.42?

**Comment by eklem** [comment]
Just a little info on Node.js version schedule:
![Node.js LTS schedule](https://cdn-images-1.medium.com/max/800/1*FAZiwnaNMhJ-6RZs-pYGQQ.png)
Version 0.10.x will stop being supported as in maintained after October this year.

**Comment by jcortega** [comment]
I see. Thanks! We are not really bound to v0.10.42.

**Comment by fergiemcdowall** [comment]
Great- update that badboy then! ;)
