### ISSUE TITLE
Invalid non-string/buffer chunk

### ISSUE THREAD

**Issue by NGPixel** [fergiemcdowall/search-index#319]
In the documentation, to add documents via native javascript, you have the following:

```javascript
const Readable = require('stream').Readable
const s = new Readable()

s.push({
  id: '3',
  body: 'this doc has a great body'
})
```

which throws a `TypeError: Invalid non-string/buffer chunk`. Upon reading the Node stream documentation, it states that a Readable stream can only accept a string or buffer. So this example makes no sense at all.

So how can I add standard JS objects to the index?

What was the motive behind moving to a streamable API? It adds so much more complexity considering you can no longer use promises on any of the search-index methods.

**Comment by fergiemcdowall** [comment]
The docs were wrong (now fixed)

You want to instantiate your `Readable` like this:

```javascript
const s = new Readable( {objectMode: true} )
```

**Comment by fergiemcdowall** [comment]
The motive behind moving to a streamable API is to make the following stuff better:

 * Memory usage- streams handle large streams of data more efficiently
 * Document processing- streams allow much cleaner and more extenable document processing.
 * Composability- You can plug streams into each other very easily. You can for example make and aggregation (bucket, category) and then `.pipe` in into `.get` in order to create a set of documents.
 * Better handling of remote data.

See also https://jakearchibald.com/2016/streams-ftw/

It should still be possible to promisify streams, which I agree may be nicer for some query applications.

**Comment by fergiemcdowall** [comment]
Just an FYI: All the streamable queries (apart from the memory intensive replication ones) are going to get callback aliases so that the library can be run in the browser without additional libraries (highland etc.). Once streams are a thing in the browser, then we might consider not having callbacks.
