### ISSUE TITLE
How to be notified if indexing of batch completed

### ISSUE THREAD

**Issue by aschilling** [fergiemcdowall/search-index#331]
Hi,

I am doing my first steps with search-index and I am really fascinated, great job. One thing, which was not easy for me, was finding out that errors in the form "TypeError: docVector is undefined" are normal when querying the search index as long as it did not finish indexing all text. Don't you think that this is something, which could be made more apparent in the documentation?

Moreover, I would like to ask if there is a way to be notified if the indexing finished and I such errors do no longer occur when querying the search index

**Comment by fergiemcdowall** [comment]
I tend to index stuff in this way. "error" and "end" events are caught as shown.

```javascript
    var s = new Readable({ objectMode: true })
    var doc = {
      id: '2',
      title: 'Mad Science is on the Rise',
      body: 'Mad,  mad things are happening.'
    }
    s.push(doc)
    s.push(null)
    s.pipe(si.defaultPipeline())
      .pipe(si.add())
      .on('data', function (data) {})
      .on('error', function (error) {
        // there was an error (look inside "error" variable)
      })
      .on('end', function () {
        // everything is indexed
      })
```

**Comment by aschilling** [comment]
Thank you very much for the clarification. In case of the browserified example (search-index/doc/demo/searchapp.js) where would I put this pipe example?

**Comment by fergiemcdowall** [comment]
`Readable` is a part of the node API, and therefore only works in Node applications. To do indexing in the browser you need you have the following options:

 * Use `callbackyAdd` (non-streamed)
 * Make a node application, and then `browserify` it
 * Use a wrapper lib like `highland.js` to create a node stream from an array of docs

In case of the browserified example (search-index/doc/demo/searchapp.js) you could make it streamy by doing something like this:

Add this to the bottom of [your html](https://github.com/fergiemcdowall/search-index/blob/master/doc/demo/index.html#L28) (but above the reference your script), so that your script can use the `highland` var:

```html
<script src="https://cdn.rawgit.com/caolan/highland/2.10.1/dist/highland.min.js"></script>
```

Remove [these lines](https://github.com/fergiemcdowall/search-index/blob/master/doc/demo/searchapp.js#L24-L27) from your script and replace them with the following:

```javascript
  highland(data)
    .pipe(mySearchIndex.defaultPipeline())
    .pipe(mySearchIndex.add())
    .on('data', function (data) {})
    .on('error', function (error) {
      // there was an error (look inside "error" variable)
    })
    .on('end', function () {
      // everything is indexed
      search()
    })
```

**Comment by fergiemcdowall** [comment]
PS: using highland is of course an extra download, but since it is fairly popular, it will probably be cached on the network and therefore fairly fast. You might decide that browserify, or vanilla callbacks are better.

[The new fetch API is hopefully going to be pipeable in the near future](https://jakearchibald.com/2016/streams-ftw/)- so it will be really easy to pipe data into the browser

**Comment by fergiemcdowall** [comment]
Closing- please reopen if more info is needed
