### ISSUE TITLE
How search for values having ',' in the field

### ISSUE THREAD

**Issue by AnnamrajuSarvani** [fergiemcdowall/search-index#397]
Hi,
https://gist.github.com/AnnamrajuSarvani/813178d9389a67df725c7f0f090bd74f
In the above sample I have data in arrays. I want to search inside array field whose values are "Linseed, Linpep" searching with "linseed, linpep" also doesn't work.
If I search for above values returns empty. How to search in array fields?
Please help me

**Comment by AnnamrajuSarvani** [comment]
How tokenizer works for such fields?
I tried with and without separators options.

**Comment by fergiemcdowall** [comment]
You cant do that

**Comment by eklem** [comment]
Arrays are for categorizing, isn't it?

**Comment by AnnamrajuSarvani** [comment]
I see you have changed value from 
 ["veg-oil", "Linseed, Linpep", "lin-oil", "soy-oil", "sun-oil", "soybean", "oilseed", "corn", "sunseed", "grain", "sorghum", "wheat"]
to this 
 "topics": ["veg-oil", "Linseed", "Linpep", "lin-oil", "soy-oil", "sun-oil", "soybean", "oilseed", "corn", "sunseed", "grain", "sorghum", "wheat"]

But I want the actual scenario to work.

**Comment by eklem** [comment]
Array fields is for filtering on categories. You do a search, and feed the same query to categorize() and get categories back to filter on.

In your example you can get back both results if you search for "wheat" since it's in both documents body fields. Then you also get a list of categories to filter on if you do the same query on categorize() and that will show "wheat" first in topics since it is a valid topic for two hits.

What is the use case that anyone will type "Linseed, Linpep"? I think you need to both look at what the real use case is and how the software is intended to work to better understand how to connect the two.

**Comment by fergiemcdowall** [comment]
@AnnamrajuSarvani you have been vague about what the actual scenario is, but assuming that you want to match `"Linseed, Linpep"` you need to skip field normalisation (which would normally remove the ",") by setting `normalise: ''` and also `preserveCase: true` in order to handle the capitalisation. I have updated the gist accordingly here: https://gist.github.com/fergiemcdowall/734a234058e955746a62b314d0fea6ea

**Comment by AnnamrajuSarvani** [comment]
sorry, I have given bad examples. I will try and let you know.
