### ISSUE TITLE
Numeric sort

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/search-index#424]
Implement

**Comment by jorinvo** [comment]
I was wondering what this issue is about. Judging from [this issue](https://github.com/fergiemcdowall/search-index/issues/414) and from trying it out like shown in the tests [here](https://github.com/fergiemcdowall/search-index/blob/b825663a024e56b0bf6b5f8e811103cf1d7b0d1d/test/node/mocha-tests/sorting-test.js#L153), sorting by numbers is working already. Is this issue an addition to this?

**Comment by fergiemcdowall** [comment]
Yes, it seems to be working.

**Comment by jorinvo** [comment]
So this issue is solved already or am I missing something?

**Comment by fergiemcdowall** [comment]
Let’s call it solved!

**Comment by jorinvo** [comment]
Cool! Any plans on adding support for alphabetical sorting for strings?
We currently keep a separate system to return sorted results, especially important for empty searches.
If you would be interested, I would open another issue. Would also be happy to help! Just not sure if there are any limitations that make this not a good idea in general..

**Comment by fergiemcdowall** [comment]
Alphabetical sort is there :)
