### ISSUE TITLE
What is the search principle of search-index?

### ISSUE THREAD

**Issue by Trinyoung** [fergiemcdowall/search-index#441]

**Comment by fergiemcdowall** [comment]
@trinyoung can you expand? What do you mean by “search principle”?

**Comment by Trinyoung** [comment]
How to search?the step

**Comment by eklem** [comment]
Is this what you're looking for? https://github.com/fergiemcdowall/search-index/blob/master/docs/search.md

If you want to understand both adding and then searching, you can check out [this example](https://github.com/fergiemcdowall/search-index/tree/master/docs/demo). The [searchapp.js](https://github.com/fergiemcdowall/search-index/blob/master/docs/demo/searchapp.js) is where it happens.

**Comment by eklem** [comment]
And since it's a streaming interface, meaning you get streaming JSON back (no commas between objects) each function does only one thing. So you need to query the matcher function to do autosuggest, query the categorize function to get back facets to filter on, and query the search function to get actual search results back.

**Comment by eklem** [comment]
Closing this @Trinyoung . Feel free to open it again if you have new comments or info.
