### ISSUE TITLE
How to use the different parts of the API?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#474]
Is it possible to do stuff like this, @fergiemcdowall :

* autocomplete on several words (matching on two, three or more words, meaning this needs to be indexed too)
* number of results
* only show a subset (i.e. 10 of 273)
* filter on more than just one word
* add an arary in an object and be able to filter on one item in that array
* show what is available to filter on
* delete everything in the index

I was thinking if I could get some hint on what is possible now and in what direction I need to check, I could do some testing myself. And make it easily available in the `[norch-vue](https://github.com/eklem/norch-vue)`

**Comment by eklem** [comment]
I'll start with this and test: https://github.com/fergiemcdowall/search-index/issues/462

Guessing `dictionary` can be used to matching and showing facets/what to filter on, and search is used to filter. Not fully understanding `bucket` and `bucketfilter` though.

**Comment by fergiemcdowall** [comment]
> 1.     autocomplete on several words (matching on two, three or more words, meaning this needs to be indexed too)

You would need to index your stuff with n-grams I think

> 2.     number of results

Working on this!

> 3.     only show a subset (i.e. 10 of 273)

You can use `limit` and `offset`

> 4.     filter on more than just one word

You can use as many words as you want to filter a result. If you tell me your use case I can give you the wuery

> 5.     add an arary in an object and be able to filter on one item in that array

Yes, you can do this

> 6.     show what is available to filter on

No, since you can now filter on anything/everything, there is no way to get up a list of "filterable" fields

> 7.     delete everything in the index

At the moment you have to manually delete the index. A `flush` command might be nice to have though...

**Comment by eklem** [comment]
Thanks, @fergiemcdowall !
I'll play around with it and document the stuff I get to work =)

For filters, it would be nice to be able to filter on i.e.:
[key]: [value]
country: United States of America

and then:
town: New York

**Comment by eklem** [comment]
And for n-grams, could I use the [ngraminator](https://github.com/fergiemcdowall/ngraminator)? And if so, how would I go about. Just create keys with array of arrays from ngraminator as value?

**Comment by eklem** [comment]
For the delete all, you can do a:

```JavaScript
db.GET('*').then( ... delete all ID's ...)
```

**Comment by eklem** [comment]
And for number of results, just count the ID's (or array.length ?). Will do for now for both number of docs in index and number of search results.

**Comment by fergiemcdowall** [comment]
update march 2021:


_autocomplete on several words (matching on two, three or more words, meaning this needs to be indexed too)_

 - This requires ngrams, which will be fixed in an upcoming release

_number of results_

 - Total number of results is now shown in resultset

_only show a subset (i.e. 10 of 273)_

 - You can use the [PAGE](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#page) functionality

_filter on more than just one word_

 - This is now possible

_add an arary in an object and be able to filter on one item in that array_

 - This is now possible

_show what is available to filter on_

 - see [FIELDS](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#fields)

_delete everything in the index_

 - see [FLUSH](https://github.com/fergiemcdowall/search-index/blob/master/docs/API.md#flush)
