### ISSUE TITLE
A browserify demo of search-index

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index#60]
A demo of  a search with search index that doesn't run any place else than the browser.

**Comment by fatso83** [comment]
How is this useful in any way? Not being snotty - just can't come up with a single use case.

**Comment by fergiemcdowall** [comment]
The general use case would be small(ish) indexes. Since `search-index` has replication functionality, a smallish index could be replicated on a browser from a content deliver network (s3, imgur(?), etc), and the user could then query the index locally, which would make for super fast query-response cycles.

**Advantages**
 * Fast for user once loaded
 * No need for an application server to serve the index
 * Persists on device in indexedDB from session to session

**Disadvantages**
 * Entire index must be always be replicated into the browser
 * Delay for user while index is replicated (although this could be negated by simply talking to a server until the index is loaded)
 * Impractical for large indexes

So in general you would consider this approach for services that:

 * Have smallish indexes
 * Are mobile-centric (and therefore may be accessed offline)
 * Are not updated very often

**Comment by fergiemcdowall** [comment]
There is now a demo buried in the source code. TODO: its use has to be properly documented.

**Comment by fergiemcdowall** [comment]
@russaa heroically fought through a ton of obstacles, and added a nice howto to the wiki https://github.com/fergiemcdowall/search-index/wiki/Browserify

**Comment by fergiemcdowall** [comment]
See also https://github.com/fergiemcdowall/search-index/tree/master/examples
