### ISSUE TITLE
What is the purpose of batchName?

### ISSUE THREAD

**Issue by mgtp** [fergiemcdowall/search-index#91]
si.add({'batchName': batchName, 'filters': filters}, data, function(err) {
  if (!err) console.log('indexed!');
});

The API implementation actually doesn't use it at all...

**Comment by eklem** [comment]
Logging?

**Comment by eklem** [comment]
That was my thought at least. If errors happen and I create batches like `[source]-[date]-[time]`, I have a better chance of figuring out what went wrong.

**Comment by fergiemcdowall** [comment]
In the past you could use batches. This was no longer the case for a while, but they are in the process of being reimplemented. Batches make it easier to administer indexing, and generally improve performance, since calibration only occurs at the end of a batch, rather than for every single document

**Comment by fergiemcdowall** [comment]
Batchname has meaning again. The point is, if you are deleting lots of data that may take many minutes, or even hours- you can track progress and points of failure more easily
