### ISSUE TITLE
OR Query 

### ISSUE THREAD

**Issue by thiyaga123** [fergiemcdowall/search-index#99]
"query": {
      "title": ["reagan"],
      "body": ["intelligence", "agency", "contra"]
    }

I assume above query meant 
```javascript
Get all the document that has title have word "reagan" AND  Body have "intelligence" AND "agency" AND "contra"
```
right ?

Is it possible to have combination of some  AND or OR conditions

**Comment by fergiemcdowall** [comment]
Yes, `search-index` ANDs. If you want OR, then you do two parallel queries

**Comment by eklem** [comment]
But if you use OR by having two parallel queries, the relevancy sorting is kind of lost? Not asking to be difficult, just to understand.

**Comment by fergiemcdowall** [comment]
As far as I understand it an OR search will always be a combination of two relevance calculations.

Since search-index returns the relevance score in its hits, blending two resultsets together is trivial.

Having said that, maybe search-index should have OR functionality out of the box? Or maybe there should be some sort of query processing module that sits on top?

**Comment by eklem** [comment]
OR functionality would be great, and put in a query processing module.

**Comment by bugs181** [comment]
+1 more for `OR` functionality.

**Comment by fergiemcdowall** [comment]
OR functionality is now in place and passing tests https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/or-test.js

Documentation to follow...

**Comment by eklem** [comment]
This is great news :+1:

**Comment by fergiemcdowall** [comment]
Syntax will probably change...

**Comment by fergiemcdowall** [comment]
0.8.0 supports AND, OR and NOT
